[package]
name = "gpu"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib", "lib"]

[dependencies]
spirv-std = { version = "0.4.0", features = ["glam"] }
shared = { path = "../shared" }
cfg-if = "1.0.0"
