[package]
name = "society-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkan = { path = "vulkan" }
anyhow = "1.0.68"
cfg-if = "1.0.0"
docfg = "0.1.0"

[workspace]
members = ["vulkan", "vulkan/proc"]